apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-model-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diabetes-model
  template:
    metadata:
      labels:
        app: diabetes-model
    spec:
      containers:
        - name: diabetes-model
          image: krishna354/diabetes-model-demo:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: diabetes-model-service
spec:
  type: NodePort
  selector:
    app: diabetes-model
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
